name: spectral-Demo
# Controls when the action will run. 
on:
  schedule:
    - cron: "*/6 0 * * *"
  workflow_dispatch:
    
env:
  SPECTRAL_DSN: ${{ secrets.SPECTRAL_DSN }}
  Github_token: ${{ secrets.OFIRSTOKEN }}

jobs:
  build:
    strategy:
      matrix:
        orgs: [dome9, alibaba, jeremylong, ciscodevnet,postmanlabs, ACME-Corp-Demo ]
    name: Spectral
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install
        uses: spectralops/spectral-github-action@v1
        with:
          spectral-dsn: ${{ secrets.SPECTRAL_DSN }}
          github-token: ${{ secrets.OFIRSTOKEN }}
      - name: Scan
        run: spectral scan --ok --include-tags base,audit3,iac
      - name: Scan Orgs
        run: spectral github -k org -t ${{ secrets.OFIRSTOKEN }} @${{ matrix.orgs }} --include-tags base
